// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzbpmqoolkoclxsrzcqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6YnBtcW9vbGtvY2x4c3J6Y3F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5NjM0NjksImV4cCI6MjA1NDUzOTQ2OX0.7g8z7Zsb2gJGNAqzv6qq1jdbRYWfO3SGIgo0HPexdyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);